[package]
name = "piggybank-meta"
version = "0.2.3"
authors = ["Julian Ćwirko <julian.cwirko@gmail.com>"]
edition = "2018"
publish = false

[dependencies.piggybank]
path = ".."

[dependencies.elrond-wasm]
version = "0.32.0"

[dependencies.elrond-wasm-debug]
version = "0.32.0"
